[project]
name = "yolo-autoresearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.3",
    "ipython>=9.12.0",
    "langchain-mcp-adapters>=0.2.2",
    "langchain-ollama>=1.1.0",
    "langgraph>=1.1.6",
    "mcp>=1.27.0",
    "streamlit>=1.56.0",
    "ultralytics>=8.4.36",
]
